In [ ]:
!pip install kaggle

In [6]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

The syntax of the command is incorrect.
'cp' is not recognized as an internal or external command,
operable program or batch file.
'chmod' is not recognized as an internal or external command,
operable program or batch file.

In [7]:
!kaggle datasets download shreyanshkhandelwal/goal-dataset-top-5-european-leagues

Downloading goal-dataset-top-5-european-leagues.zip to C:\Users\Asani\Data Science Amman

  0%|          | 0.00/174k [00:00<?, ?B/s]
100%|##########| 174k/174k [00:00<00:00, 281kB/s]
100%|##########| 174k/174k [00:00<00:00, 281kB/s]

In [20]:
from zipfile import ZipFile
dataset = 'Data\goal-dataset-top-5-european-leagues.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted

In [21]:
import pandas as pd
import numpy as np
import zipfile

In [23]:
df = pd.read_csv('Ligue_1-goalScorer(20-21).csv')

In [24]:
df.head(10)

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,3423,Kylian Mbappe-Lottin,31,2392,27,22.854565,7,5.384129,103,33,5,0,F M S,Paris Saint Germain,21,18.294126,32.028040,10.398179
1,1,555,Memphis Depay,37,2932,21,16.249495,12,14.070531,110,94,4,0,F M S,Lyon,13,10.168800,28.869875,12.154926
2,2,3210,Wissam Ben Yedder,37,2658,20,20.224992,7,6.692252,81,41,3,0,F S,Monaco,10,11.103916,21.631080,7.890264
3,3,83,Kevin Volland,35,2820,16,11.136245,7,5.541549,56,32,4,0,F M S,Monaco,16,11.136245,18.232254,4.062310
4,4,3746,Gaetan Laborde,38,3297,16,11.377969,8,5.432969,101,37,3,0,F M,Montpellier,16,11.377969,15.379737,4.294905
5,5,6905,Ludovic Ajorque,35,2983,16,15.859640,4,3.360381,69,35,5,0,F S,Strasbourg,12,12.059164,16.349550,1.860937
6,6,8637,Burak Yilmaz,28,2057,16,10.406690,5,4.224033,66,29,6,0,F S,Lille,12,7.366310,11.470707,1.594035
7,7,3530,Andy Delort,30,2516,15,12.927485,9,6.786704,91,53,4,0,F,Montpellier,15,12.167390,17.666918,4.133095
8,8,5657,Karl Toko Ekambi,35,2849,14,17.977210,6,6.999955,90,49,3,0,F M S,Lyon,14,17.977210,28.031234,8.084193
9,9,7224,Boulaye Dia,36,2974,14,13.288509,1,2.009202,63,29,2,0,F M S,Reims,9,9.488033,13.300803,2.334696

In [25]:
df.drop(columns='Unnamed: 0', inplace=True)

In [26]:
df.head(10)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,3423,Kylian Mbappe-Lottin,31,2392,27,22.854565,7,5.384129,103,33,5,0,F M S,Paris Saint Germain,21,18.294126,32.028040,10.398179
1,555,Memphis Depay,37,2932,21,16.249495,12,14.070531,110,94,4,0,F M S,Lyon,13,10.168800,28.869875,12.154926
2,3210,Wissam Ben Yedder,37,2658,20,20.224992,7,6.692252,81,41,3,0,F S,Monaco,10,11.103916,21.631080,7.890264
3,83,Kevin Volland,35,2820,16,11.136245,7,5.541549,56,32,4,0,F M S,Monaco,16,11.136245,18.232254,4.062310
4,3746,Gaetan Laborde,38,3297,16,11.377969,8,5.432969,101,37,3,0,F M,Montpellier,16,11.377969,15.379737,4.294905
5,6905,Ludovic Ajorque,35,2983,16,15.859640,4,3.360381,69,35,5,0,F S,Strasbourg,12,12.059164,16.349550,1.860937
6,8637,Burak Yilmaz,28,2057,16,10.406690,5,4.224033,66,29,6,0,F S,Lille,12,7.366310,11.470707,1.594035
7,3530,Andy Delort,30,2516,15,12.927485,9,6.786704,91,53,4,0,F,Montpellier,15,12.167390,17.666918,4.133095
8,5657,Karl Toko Ekambi,35,2849,14,17.977210,6,6.999955,90,49,3,0,F M S,Lyon,14,17.977210,28.031234,8.084193
9,7224,Boulaye Dia,36,2974,14,13.288509,1,2.009202,63,29,2,0,F M S,Reims,9,9.488033,13.300803,2.334696

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            575 non-null    int64
 1   player_name   575 non-null    object
 2   games         575 non-null    int64
 3   time          575 non-null    int64
 4   goals         575 non-null    int64
 5   xG            575 non-null    float64
 6   assists       575 non-null    int64
 7   xA            575 non-null    float64
 8   shots         575 non-null    int64
 9   key_passes    575 non-null    int64
 10  yellow_cards  575 non-null    int64
 11  red_cards     575 non-null    int64
 12  position      575 non-null    object
 13  team_title    575 non-null    object
 14  npg           575 non-null    int64
 15  npxG          575 non-null    float64
 16  xGChain       575 non-null    float64
 17  xGBuildup     575 non-null    float64
dtypes: float64(5), int64(10), object(3)
memory usage: 81.0+ KB