## Import Package

In [1]:
import numpy as np
import pandas as pd

In [5]:
#Membuka Dataset
df = pd.read_csv ('Data/CerealEdit.csv',index_col= 'Unnamed: 0')
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,320.0,FDA_25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [6]:
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     float64
 10  potass    77 non-null     float64
 11  vitamins  77 non-null     object
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(7), int64(5), object(4)
memory usage: 10.2+ KB

### GroupBy

In [10]:
df.groupby('shelf').mean(numeric_only=True)

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,weight,cups,rating
shelf,,,,,,,,,,,
1,102.500000,2.650000,0.60,176.250000,1.685000,16.350000,5.450000,75.500000,0.991500,0.897000,46.145439
2,109.523810,1.904762,1.00,145.714286,0.904762,13.619048,9.619048,73.095238,1.015714,0.911429,34.972827
3,107.777778,2.861111,1.25,158.611111,3.138889,14.500000,6.527778,138.750000,1.058889,0.726111,45.220032

In [11]:
df.groupby('fat').mean(numeric_only=True)

,calories,protein,sodium,fiber,carbo,sugars,potass,shelf,weight,cups,rating
fat,,,,,,,,,,,
0,95.925926,2.37037,137.962963,2.148148,16.259259,4.703704,89.444444,2.000000,0.968889,0.872963,51.778261
1,107.000000,2.40000,181.166667,2.116667,14.250000,8.200000,103.666667,2.200000,1.048667,0.832333,38.855205
2,118.571429,3.00000,175.000000,2.085714,13.750000,8.785714,123.928571,2.357143,1.118571,0.721429,36.446123
3,130.000000,3.00000,134.000000,2.600000,13.600000,8.400000,129.000000,2.800000,1.000000,0.716000,35.472138
5,120.000000,3.00000,15.000000,2.000000,8.000000,8.000000,135.000000,3.000000,1.000000,1.000000,33.983679

In [12]:
df.groupby(['fat','shelf']).mean(numeric_only=True)

             calories   protein      sodium     fiber      carbo     sugars  \
fat shelf
0   1      101.818182  2.272727  159.545455  1.181818  18.000000   4.545455
    2      102.000000  2.200000   62.000000  1.800000  14.800000   7.600000
    3       87.272727  2.545455  150.909091  3.272727  15.181818   3.545455
1   1      101.666667  2.500000  216.666667  2.416667  15.250000   6.000000
    2      110.833333  1.833333  162.500000  0.583333  13.583333  10.500000
    3      105.833333  2.916667  182.083333  3.500000  14.416667   7.000000
2   1      106.666667  4.333333  156.666667  2.066667  12.500000   7.666667
    2      113.333333  2.000000  196.666667  1.000000  12.000000   9.666667
    3      125.000000  2.875000  173.750000  2.500000  14.875000   8.875000
3   2      120.000000  1.000000  210.000000  0.000000  13.000000   9.000000
    3      132.500000  3.500000  115.000000  3.250000  13.750000   8.250000
5   3      120.000000  3.000000   15.000000  2.000000   8.000000   8.000000

               potass    weight      cups     rating
fat shelf
0   1       57.727273  0.984545  0.948182  48.540019
    2      112.000000  1.000000  0.960000  50.239967
    3      110.909091  0.939091  0.758182  55.715727
1   1       98.333333  1.000000  0.806667  42.977605
    2       62.916667  1.027500  0.930833  31.513644
    3      147.083333  1.094167  0.746667  44.135565
2   1       95.000000  1.000000  0.890000  43.700977
    2       58.333333  1.000000  0.806667  28.414072
    3      159.375000  1.207500  0.626250  36.737572
3   2       45.000000  1.000000  0.750000  19.823573
    3      150.000000  1.000000  0.707500  39.384279
5   3      135.000000  1.000000  1.000000  33.983679

In [13]:
df.groupby(['fat','shelf']).count()

           name  mfr  type  calories  protein  sodium  fiber  carbo  sugars  \
fat shelf
0   1        11   11    11        11       11      11     11     11      11
    2         5    5     5         5        5       5      5      5       5
    3        11   11    11        11       11      11     11     11      11
1   1         6    6     6         6        6       6      6      6       6
    2        12   12    12        12       12      12     12     12      12
    3        12   12    12        12       12      12     12     12      12
2   1         3    3     3         3        3       3      3      3       3
    2         3    3     3         3        3       3      3      3       3
    3         8    8     8         8        8       8      8      8       8
3   2         1    1     1         1        1       1      1      1       1
    3         4    4     4         4        4       4      4      4       4
5   3         1    1     1         1        1       1      1      1       1

           potass  vitamins  weight  cups  rating
fat shelf
0   1          11        11      11    11      11
    2           5         5       5     5       5
    3          11        11      11    11      11
1   1           6         6       6     6       6
    2          12        12      12    12      12
    3          12        12      12    12      12
2   1           3         3       3     3       3
    2           3         3       3     3       3
    3           8         8       8     8       8
3   2           1         1       1     1       1
    3           4         4       4     4       4
5   3           1         1       1     1       1

## Menambahkan kolom baru

In [14]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,320.0,FDA_25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [15]:
df.isna().sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [16]:
df.shape

(77, 16)

In [17]:
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [18]:
len(df)

77

In [19]:
df['kolom_baru'] = np.random.rand(len(df))

In [20]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,kolom_baru
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973,0.338822
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679,0.202416
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505,0.281910
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912,0.768268
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,320.0,FDA_25,3,1.0,0.75,34.384843,0.108187

In [21]:
df.drop(columns='kolom_baru', inplace=True)

In [23]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,320.0,FDA_25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,FDA_25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,FDA_25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,FDA_25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,FDA_25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,FDA_25,1,1.0,0.75,36.187559

In [ ]:
Tugas
Mengulang dari Missing Value sampe akhir
Cari Data Sendiri